### ISSUE TITLE
Issue 1 - Jon

### ISSUE THREAD

**Issue by NoelE1** [NoelE1/so4#1]
Det här är vad Jon ska göra på projektet:

Currently, the player can increase their stats through various skills in the skill tree (Luck, Evasion, Shield Efficiency). Only some of these stats currently have an effect in the game (Shield Efficiency, Hull Mastery, and Evasion) However, many of these stats have no effect in the game. You should implement the remaining stats so that they provide actual bonuses. The stats that need to be implemented are: Luck, Energy Weapon Mastery, Kinetic Weapon Mastery, Missile Mastery.

**Comment by nti1234567890** [comment]
I added the modifiers to the stats so that they would have effects when they would be upgraded.
