### ISSUE TITLE
Issue 4 - Emil N och Emil W

### ISSUE THREAD

**Issue by NoelE1** [NoelE1/so4#4]
Ni 2 får jobba på samma uppgift tillsammans, detta är vad ni ska göra:

Currently, player health and shield values don’t persist across jumps, or after docking and undocking from a station. Player health should persist, and a repair function added to stations, so that the player can repair their ship after combat.

**Comment by EmilNiord** [comment]
Vi har fixat så att health och shield sparas när man dockar och jumpar. La till repair knapp i menyn efter man dockat där man kan laga skäppet.
